# Generated by Django 3.0.8 on 2020-08-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0006_preguntafrecuente'),
        ('usuarios', '0003_remove_estudiante_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, help_text='Observación sobre la matrícula', null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ciclo_lectivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.CicloLectivo')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Estudiante')),
                ('paralelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Paralelo')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
    ]
