# Generated by Django 3.0.8 on 2020-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='matricula_aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
