# Generated by Django 3.0.8 on 2020-08-07 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200806_2336'),
        ('institucion', '0006_preguntafrecuente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0002_matricula_matricula_aceptada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_matricula', models.CharField(choices=[(1, 'ORDINARIA'), (2, 'EXTRAORDINARIA')], default='1', max_length=50)),
                ('viene_otra_institucion', models.CharField(choices=[(1, 'SI'), (2, 'NO'), (3, 'PASE')], default='1', max_length=50)),
                ('f_aceptación', models.DateField(blank=True, null=True)),
                ('aprovacion', models.BooleanField(default=False)),
                ('ciclo_lectivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.CicloLectivo')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Estudiante')),
                ('paralelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Paralelo')),
                ('rector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rector', to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Representante')),
            ],
            options={
                'verbose_name': 'SolicitudIngreso',
                'verbose_name_plural': 'SolicitudesIngresos',
            },
        ),
    ]
