# Generated by Django 3.0.8 on 2020-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20200811_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudingreso',
            name='tipo_matricula',
            field=models.CharField(choices=[('1', 'ORDINARIA'), ('2', 'EXTRAORDINARIA')], default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudingreso',
            name='viene_otra_institucion',
            field=models.CharField(choices=[('1', 'SI'), ('2', 'NO'), ('3', 'PASE')], default='1', max_length=50),
        ),
    ]
