# Generated by Django 3.0.8 on 2020-08-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_auto_20200811_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudingreso',
            old_name='aprovacion',
            new_name='aprobacion',
        ),
    ]
