# Generated by Django 3.0.8 on 2020-08-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_auto_20200811_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudingreso',
            old_name='f_aceptación',
            new_name='f_aceptacion',
        ),
    ]
