# Generated by Django 3.0.8 on 2020-07-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_nacimiento', models.DateField(help_text='Fecha de nacimiento')),
                ('lugar_nacimiento', models.CharField(help_text='Sector/Canton/Provincia', max_length=13)),
                ('img_perfil', models.ImageField(help_text='Escoja una Imagen de perfil', upload_to='')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Institucion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'NivelEducativo',
                'verbose_name_plural': 'NivelesEducativos',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_ruc', models.CharField(help_text='Cedula o RUC', max_length=13)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Padres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padres_familia', models.CharField(choices=[('M', 'Mamá'), ('P', 'Papá')], default='P', max_length=50)),
                ('is_representante', models.BooleanField(default=True, help_text='Es representante del estudiante')),
                ('nivel_educacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.NivelEducativo')),
                ('padres_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Estudiante')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Parentesco')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profesion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padres_estudiante', to='usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'Padres',
                'verbose_name_plural': 'Padres',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_estudiante', to='usuarios.Usuario'),
        ),
    ]
