# Generated by Django 3.0.8 on 2020-07-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariociclolectivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='rol',
        ),
    ]
