# Generated by Django 3.0.8 on 2020-08-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padres',
            name='is_representante',
            field=models.BooleanField(default=False, help_text='Es representante del estudiante'),
        ),
    ]
