# Generated by Django 3.0.8 on 2020-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200815_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='img_perfil',
            field=models.ImageField(help_text='Escoja una Imagen de perfil', upload_to='static/images/users'),
        ),
    ]
