# Generated by Django 3.0.8 on 2020-08-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_ciclolectivo_curso_institucionciclolectivo_paralelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclolectivo',
            name='cilo_actual',
            field=models.BooleanField(default=True, help_text='Es el año lectivo actual con el que trabajará'),
        ),
    ]
