# Generated by Django 3.0.8 on 2020-08-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_ciclolectivo_cilo_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciclolectivo',
            old_name='cilo_actual',
            new_name='ciclo_actual',
        ),
    ]
